apiVersion: apps/v1
kind: Deployment
metadata:
  name: saratube-api
  namespace: saratube-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saratube-api
  template:
    metadata:
      labels:
        app: saratube-api
    spec:
      containers:
        - name: saratube-api
          image: saratube-api:local
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: saratube-api-config
            - secretRef:
                name: saratube-api-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
