apiVersion: v1
kind: Secret
metadata:
  name: saratube-api-secret
  namespace: saratube-app
type: Opaque
stringData:
  DB_HOST: saratube-postgres-service.saratube-data.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: saratube
  DB_USER: saratube_user
  DB_PASSWORD: ChangeMeStrong123!
