name: Deploy SaraTube Backend API

on:
  push:
    branches:
      - hardening/docker-security-baseline
    paths:
      - "backend-api/**"
      - ".github/workflows/deploy-backend-api.yml"

  workflow_dispatch:

permissions:
  contents: read
  id-token: write
